### ISSUE TITLE
nothing gets downloaded

### ISSUE THREAD

**Issue by Zamtron** [JTBrinkmann/Dubtrack-Playlist-Pusher#6]
After clicking the "download" button or downloading all playlist, my browser (Google Chrome) does not download any .json files and/or zip files.

**Comment by JTBrinkmann** [comment]
I just tested it multiple times with Opera (45.0.2552.888) and Google Chrome (59.0.3071.86) on Windows (with and without addons) and it worked just fine for me (see screenshots below).

Can you please give me more details about what you saw when you tried to export your playlists? Did you see the loading-indicator ("spinner") after clicking the playlist's name or the Download All button? When clicking the Download All button, do you see a countdown? Does the countdown freeze or does it finish ("Downloaded All ✔")?

Maybe you were running an addon that blocked the Dubtrack Playlist Pusher, but I doubt that any addon would interfere (except for maybe uMatrix or ScriptSafe). Can you try again without addons (hint: addons are disabled by default in Incoknito Mode)

Screenshots:
![Chrome screenshot while Dubtrack Playlist Pusher is loading playlists](https://user-images.githubusercontent.com/1379744/27146736-a2706f5e-513a-11e7-9cc5-182a4c518198.png)
![Chrome screenshot after zip of all playlists is downloaded](https://user-images.githubusercontent.com/1379744/27146742-a58b811a-513a-11e7-86e7-6995f58efe4a.png)
